model:
  _target_: src.model.modules.diffusion.DiffusionModule
  network:
    _target_: pl_bolts.models.vision.unet.UNet
    num_classes: 1
    input_channels: 1
  loss:
    _target_: torch.nn.MSELoss
datamodule:
  data_dir: ./data
  data_loaders:
    train:
      batch_size: 8
      shuffle: True
    val:
      batch_size: 8
      shuffle: False
    test:
      batch_size: 8
      shuffle: False
hydra:
  run:
    dir: logs/${now:%Y%m%d_%H%M%S}