model:
  _target_: src.model.modules.diffusion.DiffusionModule
  network:
    _target_: pl_bolts.models.vision.unet.UNet
    num_classes: 1
    input_channels: 1
  loss:
    _target_: torch.nn.MSELoss
datamodule:
  _target_: src.data.modules.image.ImageDataModule
  data_dir: ./data
  data_loaders:
    train:
      batch_size: 8
      shuffle: True
    val:
      batch_size: 8
      shuffle: False
    test:
      batch_size: 8
      shuffle: False
trainer:
  _target_: pytorch_lightning.Trainer
  max_epochs: 10
  fast_dev_run: True
hydra:
  run:
    dir: logs/${now:%Y%m%d_%H%M%S}