defaults:
  - trainer: debug

global:
  max_time_steps: 1000
model:
  _target_: src.model.modules.diffusion_module.DiffusionModule
  network:
    _target_: src.model.network.unet.UNet
    in_size: 1
    out_size: 1
    num_layers: 5
    max_time_steps: ${global.max_time_steps}
    t_emb_size: 1024
  loss:
    _target_: torch.nn.MSELoss
  t_max: ${global.max_time_steps}
  beta_scheduler:
    _target_: src.model.beta_scheduler.BetaScheduler
    type: cosine
datamodule:
  _target_: src.data.modules.image.ImageDataModule
  data_dir: ${data_dir}
  data_loaders:
    train:
      batch_size: 8
      shuffle: True
      num_workers: 8
    val:
      batch_size: 8
      shuffle: False
      num_workers: 8
    test:
      batch_size: 8
      shuffle: False
      num_workers: 8
callbacks:
  model_checkpoints:
    _target_: pytorch_lightning.callbacks.ModelCheckpoint
    save_last: True
    dirpath: "checkpoints/"
    filename: "{epoch}"
    save_top_k: -1
    save_on_train_epoch_end: True
    save_weights_only: False

work_dir: ${hydra:runtime.cwd}
data_dir: ${work_dir}/data

name: test

hydra:
  run:
    dir: logs/${now:%Y%m%d_%H%M%S}
