name: simple_diffusion
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - python==3.8
  - matplotlib
  - opencv
  - imageio
  - ipykernel
  - pytorch-lightning
  - lightning-bolts
  - hydra
  - black
  - torchvision
  - ca-certificates
  - certifi
  - openssl
  - einops
  - flake8
  - isort
  - mypy
